export {globalStorage, globalStorageMMKV} from './global-storage'
export {
  STORAGE_EXPENSE_LAST_CATEGORY_ID,
  STORAGE_INCOME_LAST_CATEGORY_ID,
  STORAGE_CONSTANT_LAST_ACCOUNT_ID,
  STORAGE_CONSTANT_LAST_PAYWALL_DATE,
  STORAGE_CONSTANT_NUMBER_OF_TRANSACTIONS,
  STORAGE_FIRST_CURRENCY,
} from './const'
