import colors from 'tailwindcss/colors'

export const colorsSecondary = {
  slate: {light: colors.slate[200], dark: colors.slate[600]},
  gray: {light: colors.gray[400], dark: colors.gray[800]},
  zinc: {light: colors.zinc[200], dark: colors.zinc[700]},
  neutral: {light: colors.neutral[200], dark: colors.neutral[700]},
  stone: {light: colors.stone[200], dark: colors.stone[700]},
  red: {light: colors.red[200], dark: colors.red[700]},
  orange: {light: colors.orange[200], dark: colors.orange[700]},
  amber: {light: colors.amber[200], dark: colors.amber[700]},
  yellow: {light: colors.yellow[200], dark: colors.yellow[700]},
  lime: {light: colors.lime[200], dark: colors.lime[700]},
  green: {light: colors.green[200], dark: colors.green[700]},
  emerald: {light: colors.emerald[200], dark: colors.emerald[700]},
  teal: {light: colors.teal[200], dark: colors.teal[700]},
  cyan: {light: colors.cyan[200], dark: colors.cyan[700]},
  sky: {light: colors.sky[200], dark: colors.sky[700]},
  blue: {light: colors.blue[200], dark: colors.blue[700]},
  indigo: {light: colors.indigo[200], dark: colors.indigo[700]},
  violet: {light: colors.violet[200], dark: colors.violet[700]},
  purple: {light: colors.purple[200], dark: colors.purple[700]},
  fuchsia: {light: colors.fuchsia[200], dark: colors.fuchsia[700]},
  pink: {light: colors.pink[200], dark: colors.pink[700]},
  rose: {light: colors.rose[200], dark: colors.rose[700]},
}
