name: 'Release App'

on:
  workflow_dispatch:
    inputs:
      use_self_hosted:
        type: boolean
        description: 'Use self-hosted runner'
        default: false
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ${{ github.event.inputs.use_self_hosted == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    outputs:
      app--tag_name: ${{ steps.release.outputs.tag_name }}
      app--release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: '🏗 Setup repo'
        uses: actions/checkout@v6

      - name: 'Release-please'
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token:  ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
